//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tramites.Servicio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/EntidadesCompartidas")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Tramites.Servicio.Solicitante))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Tramites.Servicio.Empleado))]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CedulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseñaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cedula {
            get {
                return this.CedulaField;
            }
            set {
                if ((this.CedulaField.Equals(value) != true)) {
                    this.CedulaField = value;
                    this.RaisePropertyChanged("Cedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contraseña {
            get {
                return this.ContraseñaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseñaField, value) != true)) {
                    this.ContraseñaField = value;
                    this.RaisePropertyChanged("Contraseña");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Solicitante", Namespace="http://schemas.datacontract.org/2004/07/EntidadesCompartidas")]
    [System.SerializableAttribute()]
    public partial class Solicitante : Tramites.Servicio.Usuario {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empleado", Namespace="http://schemas.datacontract.org/2004/07/EntidadesCompartidas")]
    [System.SerializableAttribute()]
    public partial class Empleado : Tramites.Servicio.Usuario {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoraFinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoraInicioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HoraFin {
            get {
                return this.HoraFinField;
            }
            set {
                if ((object.ReferenceEquals(this.HoraFinField, value) != true)) {
                    this.HoraFinField = value;
                    this.RaisePropertyChanged("HoraFin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HoraInicio {
            get {
                return this.HoraInicioField;
            }
            set {
                if ((object.ReferenceEquals(this.HoraInicioField, value) != true)) {
                    this.HoraInicioField = value;
                    this.RaisePropertyChanged("HoraInicio");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Documentacion", Namespace="http://schemas.datacontract.org/2004/07/EntidadesCompartidas")]
    [System.SerializableAttribute()]
    public partial class Documentacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LugarObtencionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LugarObtencion {
            get {
                return this.LugarObtencionField;
            }
            set {
                if ((object.ReferenceEquals(this.LugarObtencionField, value) != true)) {
                    this.LugarObtencionField = value;
                    this.RaisePropertyChanged("LugarObtencion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HorasExtras", Namespace="http://schemas.datacontract.org/2004/07/EntidadesCompartidas")]
    [System.SerializableAttribute()]
    public partial class HorasExtras : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Tramites.Servicio.Empleado EmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MinutosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Tramites.Servicio.Empleado Empleado {
            get {
                return this.EmpleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpleadoField, value) != true)) {
                    this.EmpleadoField = value;
                    this.RaisePropertyChanged("Empleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Minutos {
            get {
                return this.MinutosField;
            }
            set {
                if ((this.MinutosField.Equals(value) != true)) {
                    this.MinutosField = value;
                    this.RaisePropertyChanged("Minutos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Solicitud", Namespace="http://schemas.datacontract.org/2004/07/EntidadesCompartidas")]
    [System.SerializableAttribute()]
    public partial class Solicitud : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Tramites.Servicio.Solicitante SolicitaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Tramites.Servicio.TiposdeTramite UnTramiteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((this.NumeroField.Equals(value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Tramites.Servicio.Solicitante Solicita {
            get {
                return this.SolicitaField;
            }
            set {
                if ((object.ReferenceEquals(this.SolicitaField, value) != true)) {
                    this.SolicitaField = value;
                    this.RaisePropertyChanged("Solicita");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Tramites.Servicio.TiposdeTramite UnTramite {
            get {
                return this.UnTramiteField;
            }
            set {
                if ((object.ReferenceEquals(this.UnTramiteField, value) != true)) {
                    this.UnTramiteField = value;
                    this.RaisePropertyChanged("UnTramite");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TiposdeTramite", Namespace="http://schemas.datacontract.org/2004/07/EntidadesCompartidas")]
    [System.SerializableAttribute()]
    public partial class TiposdeTramite : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Tramites.Servicio.Documentacion[] DocumentoListaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PrecioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Tramites.Servicio.Documentacion[] DocumentoLista {
            get {
                return this.DocumentoListaField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentoListaField, value) != true)) {
                    this.DocumentoListaField = value;
                    this.RaisePropertyChanged("DocumentoLista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Servicio.IServicio")]
    public interface IServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/BuscarDocumentacionActiva", ReplyAction="http://tempuri.org/IServicio/BuscarDocumentacionActivaResponse")]
        Tramites.Servicio.Documentacion BuscarDocumentacionActiva(int codigo, Tramites.Servicio.Empleado EmpleadoActual);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/BuscarDocumentacionActiva", ReplyAction="http://tempuri.org/IServicio/BuscarDocumentacionActivaResponse")]
        System.Threading.Tasks.Task<Tramites.Servicio.Documentacion> BuscarDocumentacionActivaAsync(int codigo, Tramites.Servicio.Empleado EmpleadoActual);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/AltaDocumentacion", ReplyAction="http://tempuri.org/IServicio/AltaDocumentacionResponse")]
        void AltaDocumentacion(Tramites.Servicio.Documentacion oDocumentacion, Tramites.Servicio.Empleado EmpleadoActual);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/AltaDocumentacion", ReplyAction="http://tempuri.org/IServicio/AltaDocumentacionResponse")]
        System.Threading.Tasks.Task AltaDocumentacionAsync(Tramites.Servicio.Documentacion oDocumentacion, Tramites.Servicio.Empleado EmpleadoActual);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ModificarDocumentacion", ReplyAction="http://tempuri.org/IServicio/ModificarDocumentacionResponse")]
        void ModificarDocumentacion(Tramites.Servicio.Documentacion oDocumentacion, Tramites.Servicio.Empleado EmpleadoActual);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ModificarDocumentacion", ReplyAction="http://tempuri.org/IServicio/ModificarDocumentacionResponse")]
        System.Threading.Tasks.Task ModificarDocumentacionAsync(Tramites.Servicio.Documentacion oDocumentacion, Tramites.Servicio.Empleado EmpleadoActual);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/BajaDocumentacion", ReplyAction="http://tempuri.org/IServicio/BajaDocumentacionResponse")]
        void BajaDocumentacion(Tramites.Servicio.Documentacion oDocumentacion, Tramites.Servicio.Empleado EmpleadoActual);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/BajaDocumentacion", ReplyAction="http://tempuri.org/IServicio/BajaDocumentacionResponse")]
        System.Threading.Tasks.Task BajaDocumentacionAsync(Tramites.Servicio.Documentacion oDocumentacion, Tramites.Servicio.Empleado EmpleadoActual);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarDocumentacion", ReplyAction="http://tempuri.org/IServicio/ListarDocumentacionResponse")]
        Tramites.Servicio.Documentacion[] ListarDocumentacion(Tramites.Servicio.Empleado EmpleadoActual);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarDocumentacion", ReplyAction="http://tempuri.org/IServicio/ListarDocumentacionResponse")]
        System.Threading.Tasks.Task<Tramites.Servicio.Documentacion[]> ListarDocumentacionAsync(Tramites.Servicio.Empleado EmpleadoActual);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/AltaHorasExtra", ReplyAction="http://tempuri.org/IServicio/AltaHorasExtraResponse")]
        void AltaHorasExtra(Tramites.Servicio.HorasExtras oHorasExtra, Tramites.Servicio.Empleado EmpleadoActual);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/AltaHorasExtra", ReplyAction="http://tempuri.org/IServicio/AltaHorasExtraResponse")]
        System.Threading.Tasks.Task AltaHorasExtraAsync(Tramites.Servicio.HorasExtras oHorasExtra, Tramites.Servicio.Empleado EmpleadoActual);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/AltaSolicitud", ReplyAction="http://tempuri.org/IServicio/AltaSolicitudResponse")]
        void AltaSolicitud(Tramites.Servicio.Solicitud oSolicitud, Tramites.Servicio.Solicitante SolicitanteActual);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/AltaSolicitud", ReplyAction="http://tempuri.org/IServicio/AltaSolicitudResponse")]
        System.Threading.Tasks.Task AltaSolicitudAsync(Tramites.Servicio.Solicitud oSolicitud, Tramites.Servicio.Solicitante SolicitanteActual);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/CambiarEstado", ReplyAction="http://tempuri.org/IServicio/CambiarEstadoResponse")]
        void CambiarEstado(Tramites.Servicio.Solicitud oSolicitud, Tramites.Servicio.Empleado EmpleadoActual);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/CambiarEstado", ReplyAction="http://tempuri.org/IServicio/CambiarEstadoResponse")]
        System.Threading.Tasks.Task CambiarEstadoAsync(Tramites.Servicio.Solicitud oSolicitud, Tramites.Servicio.Empleado EmpleadoActual);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarSolicitudes", ReplyAction="http://tempuri.org/IServicio/ListarSolicitudesResponse")]
        Tramites.Servicio.Solicitud[] ListarSolicitudes(Tramites.Servicio.Empleado EmpleadoActual);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarSolicitudes", ReplyAction="http://tempuri.org/IServicio/ListarSolicitudesResponse")]
        System.Threading.Tasks.Task<Tramites.Servicio.Solicitud[]> ListarSolicitudesAsync(Tramites.Servicio.Empleado EmpleadoActual);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarSolicitudesAlta", ReplyAction="http://tempuri.org/IServicio/ListarSolicitudesAltaResponse")]
        Tramites.Servicio.Solicitud[] ListarSolicitudesAlta(Tramites.Servicio.Empleado EmpleadoActual);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarSolicitudesAlta", ReplyAction="http://tempuri.org/IServicio/ListarSolicitudesAltaResponse")]
        System.Threading.Tasks.Task<Tramites.Servicio.Solicitud[]> ListarSolicitudesAltaAsync(Tramites.Servicio.Empleado EmpleadoActual);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/BuscarTiposdeTramiteActivo", ReplyAction="http://tempuri.org/IServicio/BuscarTiposdeTramiteActivoResponse")]
        Tramites.Servicio.TiposdeTramite BuscarTiposdeTramiteActivo(string codigo, Tramites.Servicio.Empleado EmpleadoActual);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/BuscarTiposdeTramiteActivo", ReplyAction="http://tempuri.org/IServicio/BuscarTiposdeTramiteActivoResponse")]
        System.Threading.Tasks.Task<Tramites.Servicio.TiposdeTramite> BuscarTiposdeTramiteActivoAsync(string codigo, Tramites.Servicio.Empleado EmpleadoActual);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/AltaTiposdeTramite", ReplyAction="http://tempuri.org/IServicio/AltaTiposdeTramiteResponse")]
        void AltaTiposdeTramite(Tramites.Servicio.TiposdeTramite oTiposdeTramite, Tramites.Servicio.Empleado EmpleadoActual);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/AltaTiposdeTramite", ReplyAction="http://tempuri.org/IServicio/AltaTiposdeTramiteResponse")]
        System.Threading.Tasks.Task AltaTiposdeTramiteAsync(Tramites.Servicio.TiposdeTramite oTiposdeTramite, Tramites.Servicio.Empleado EmpleadoActual);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ModificarTiposdeTramite", ReplyAction="http://tempuri.org/IServicio/ModificarTiposdeTramiteResponse")]
        void ModificarTiposdeTramite(Tramites.Servicio.TiposdeTramite oTiposdeTramite, Tramites.Servicio.Empleado EmpleadoActual);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ModificarTiposdeTramite", ReplyAction="http://tempuri.org/IServicio/ModificarTiposdeTramiteResponse")]
        System.Threading.Tasks.Task ModificarTiposdeTramiteAsync(Tramites.Servicio.TiposdeTramite oTiposdeTramite, Tramites.Servicio.Empleado EmpleadoActual);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/BajaTiposdeTramite", ReplyAction="http://tempuri.org/IServicio/BajaTiposdeTramiteResponse")]
        void BajaTiposdeTramite(Tramites.Servicio.TiposdeTramite oTiposdeTramite, Tramites.Servicio.Empleado EmpleadoActual);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/BajaTiposdeTramite", ReplyAction="http://tempuri.org/IServicio/BajaTiposdeTramiteResponse")]
        System.Threading.Tasks.Task BajaTiposdeTramiteAsync(Tramites.Servicio.TiposdeTramite oTiposdeTramite, Tramites.Servicio.Empleado EmpleadoActual);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarTiposdeTramite", ReplyAction="http://tempuri.org/IServicio/ListarTiposdeTramiteResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Tramites.Servicio.Empleado))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Tramites.Servicio.Usuario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Tramites.Servicio.Solicitante))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Tramites.Servicio.Documentacion))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Tramites.Servicio.Documentacion[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Tramites.Servicio.HorasExtras))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Tramites.Servicio.Solicitud))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Tramites.Servicio.TiposdeTramite))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Tramites.Servicio.Solicitud[]))]
        object[] ListarTiposdeTramite(Tramites.Servicio.Usuario usuActual);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarTiposdeTramite", ReplyAction="http://tempuri.org/IServicio/ListarTiposdeTramiteResponse")]
        System.Threading.Tasks.Task<object[]> ListarTiposdeTramiteAsync(Tramites.Servicio.Usuario usuActual);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/BuscarUsuario", ReplyAction="http://tempuri.org/IServicio/BuscarUsuarioResponse")]
        Tramites.Servicio.Usuario BuscarUsuario(int cedula, Tramites.Servicio.Empleado EmpleadoActual);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/BuscarUsuario", ReplyAction="http://tempuri.org/IServicio/BuscarUsuarioResponse")]
        System.Threading.Tasks.Task<Tramites.Servicio.Usuario> BuscarUsuarioAsync(int cedula, Tramites.Servicio.Empleado EmpleadoActual);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/AltaUsuario", ReplyAction="http://tempuri.org/IServicio/AltaUsuarioResponse")]
        void AltaUsuario(Tramites.Servicio.Usuario oUsuario, Tramites.Servicio.Usuario UsuarioActual);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/AltaUsuario", ReplyAction="http://tempuri.org/IServicio/AltaUsuarioResponse")]
        System.Threading.Tasks.Task AltaUsuarioAsync(Tramites.Servicio.Usuario oUsuario, Tramites.Servicio.Usuario UsuarioActual);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ModificarUsuario", ReplyAction="http://tempuri.org/IServicio/ModificarUsuarioResponse")]
        void ModificarUsuario(Tramites.Servicio.Usuario oUsuario, Tramites.Servicio.Empleado EmpleadoActual);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ModificarUsuario", ReplyAction="http://tempuri.org/IServicio/ModificarUsuarioResponse")]
        System.Threading.Tasks.Task ModificarUsuarioAsync(Tramites.Servicio.Usuario oUsuario, Tramites.Servicio.Empleado EmpleadoActual);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/BajaUsuario", ReplyAction="http://tempuri.org/IServicio/BajaUsuarioResponse")]
        void BajaUsuario(Tramites.Servicio.Usuario oUsuario, Tramites.Servicio.Empleado EmpleadoActual);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/BajaUsuario", ReplyAction="http://tempuri.org/IServicio/BajaUsuarioResponse")]
        System.Threading.Tasks.Task BajaUsuarioAsync(Tramites.Servicio.Usuario oUsuario, Tramites.Servicio.Empleado EmpleadoActual);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/LogueoUsuario", ReplyAction="http://tempuri.org/IServicio/LogueoUsuarioResponse")]
        Tramites.Servicio.Usuario LogueoUsuario(string contra, int cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/LogueoUsuario", ReplyAction="http://tempuri.org/IServicio/LogueoUsuarioResponse")]
        System.Threading.Tasks.Task<Tramites.Servicio.Usuario> LogueoUsuarioAsync(string contra, int cedula);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioChannel : Tramites.Servicio.IServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioClient : System.ServiceModel.ClientBase<Tramites.Servicio.IServicio>, Tramites.Servicio.IServicio {
        
        public ServicioClient() {
        }
        
        public ServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Tramites.Servicio.Documentacion BuscarDocumentacionActiva(int codigo, Tramites.Servicio.Empleado EmpleadoActual) {
            return base.Channel.BuscarDocumentacionActiva(codigo, EmpleadoActual);
        }
        
        public System.Threading.Tasks.Task<Tramites.Servicio.Documentacion> BuscarDocumentacionActivaAsync(int codigo, Tramites.Servicio.Empleado EmpleadoActual) {
            return base.Channel.BuscarDocumentacionActivaAsync(codigo, EmpleadoActual);
        }
        
        public void AltaDocumentacion(Tramites.Servicio.Documentacion oDocumentacion, Tramites.Servicio.Empleado EmpleadoActual) {
            base.Channel.AltaDocumentacion(oDocumentacion, EmpleadoActual);
        }
        
        public System.Threading.Tasks.Task AltaDocumentacionAsync(Tramites.Servicio.Documentacion oDocumentacion, Tramites.Servicio.Empleado EmpleadoActual) {
            return base.Channel.AltaDocumentacionAsync(oDocumentacion, EmpleadoActual);
        }
        
        public void ModificarDocumentacion(Tramites.Servicio.Documentacion oDocumentacion, Tramites.Servicio.Empleado EmpleadoActual) {
            base.Channel.ModificarDocumentacion(oDocumentacion, EmpleadoActual);
        }
        
        public System.Threading.Tasks.Task ModificarDocumentacionAsync(Tramites.Servicio.Documentacion oDocumentacion, Tramites.Servicio.Empleado EmpleadoActual) {
            return base.Channel.ModificarDocumentacionAsync(oDocumentacion, EmpleadoActual);
        }
        
        public void BajaDocumentacion(Tramites.Servicio.Documentacion oDocumentacion, Tramites.Servicio.Empleado EmpleadoActual) {
            base.Channel.BajaDocumentacion(oDocumentacion, EmpleadoActual);
        }
        
        public System.Threading.Tasks.Task BajaDocumentacionAsync(Tramites.Servicio.Documentacion oDocumentacion, Tramites.Servicio.Empleado EmpleadoActual) {
            return base.Channel.BajaDocumentacionAsync(oDocumentacion, EmpleadoActual);
        }
        
        public Tramites.Servicio.Documentacion[] ListarDocumentacion(Tramites.Servicio.Empleado EmpleadoActual) {
            return base.Channel.ListarDocumentacion(EmpleadoActual);
        }
        
        public System.Threading.Tasks.Task<Tramites.Servicio.Documentacion[]> ListarDocumentacionAsync(Tramites.Servicio.Empleado EmpleadoActual) {
            return base.Channel.ListarDocumentacionAsync(EmpleadoActual);
        }
        
        public void AltaHorasExtra(Tramites.Servicio.HorasExtras oHorasExtra, Tramites.Servicio.Empleado EmpleadoActual) {
            base.Channel.AltaHorasExtra(oHorasExtra, EmpleadoActual);
        }
        
        public System.Threading.Tasks.Task AltaHorasExtraAsync(Tramites.Servicio.HorasExtras oHorasExtra, Tramites.Servicio.Empleado EmpleadoActual) {
            return base.Channel.AltaHorasExtraAsync(oHorasExtra, EmpleadoActual);
        }
        
        public void AltaSolicitud(Tramites.Servicio.Solicitud oSolicitud, Tramites.Servicio.Solicitante SolicitanteActual) {
            base.Channel.AltaSolicitud(oSolicitud, SolicitanteActual);
        }
        
        public System.Threading.Tasks.Task AltaSolicitudAsync(Tramites.Servicio.Solicitud oSolicitud, Tramites.Servicio.Solicitante SolicitanteActual) {
            return base.Channel.AltaSolicitudAsync(oSolicitud, SolicitanteActual);
        }
        
        public void CambiarEstado(Tramites.Servicio.Solicitud oSolicitud, Tramites.Servicio.Empleado EmpleadoActual) {
            base.Channel.CambiarEstado(oSolicitud, EmpleadoActual);
        }
        
        public System.Threading.Tasks.Task CambiarEstadoAsync(Tramites.Servicio.Solicitud oSolicitud, Tramites.Servicio.Empleado EmpleadoActual) {
            return base.Channel.CambiarEstadoAsync(oSolicitud, EmpleadoActual);
        }
        
        public Tramites.Servicio.Solicitud[] ListarSolicitudes(Tramites.Servicio.Empleado EmpleadoActual) {
            return base.Channel.ListarSolicitudes(EmpleadoActual);
        }
        
        public System.Threading.Tasks.Task<Tramites.Servicio.Solicitud[]> ListarSolicitudesAsync(Tramites.Servicio.Empleado EmpleadoActual) {
            return base.Channel.ListarSolicitudesAsync(EmpleadoActual);
        }
        
        public Tramites.Servicio.Solicitud[] ListarSolicitudesAlta(Tramites.Servicio.Empleado EmpleadoActual) {
            return base.Channel.ListarSolicitudesAlta(EmpleadoActual);
        }
        
        public System.Threading.Tasks.Task<Tramites.Servicio.Solicitud[]> ListarSolicitudesAltaAsync(Tramites.Servicio.Empleado EmpleadoActual) {
            return base.Channel.ListarSolicitudesAltaAsync(EmpleadoActual);
        }
        
        public Tramites.Servicio.TiposdeTramite BuscarTiposdeTramiteActivo(string codigo, Tramites.Servicio.Empleado EmpleadoActual) {
            return base.Channel.BuscarTiposdeTramiteActivo(codigo, EmpleadoActual);
        }
        
        public System.Threading.Tasks.Task<Tramites.Servicio.TiposdeTramite> BuscarTiposdeTramiteActivoAsync(string codigo, Tramites.Servicio.Empleado EmpleadoActual) {
            return base.Channel.BuscarTiposdeTramiteActivoAsync(codigo, EmpleadoActual);
        }
        
        public void AltaTiposdeTramite(Tramites.Servicio.TiposdeTramite oTiposdeTramite, Tramites.Servicio.Empleado EmpleadoActual) {
            base.Channel.AltaTiposdeTramite(oTiposdeTramite, EmpleadoActual);
        }
        
        public System.Threading.Tasks.Task AltaTiposdeTramiteAsync(Tramites.Servicio.TiposdeTramite oTiposdeTramite, Tramites.Servicio.Empleado EmpleadoActual) {
            return base.Channel.AltaTiposdeTramiteAsync(oTiposdeTramite, EmpleadoActual);
        }
        
        public void ModificarTiposdeTramite(Tramites.Servicio.TiposdeTramite oTiposdeTramite, Tramites.Servicio.Empleado EmpleadoActual) {
            base.Channel.ModificarTiposdeTramite(oTiposdeTramite, EmpleadoActual);
        }
        
        public System.Threading.Tasks.Task ModificarTiposdeTramiteAsync(Tramites.Servicio.TiposdeTramite oTiposdeTramite, Tramites.Servicio.Empleado EmpleadoActual) {
            return base.Channel.ModificarTiposdeTramiteAsync(oTiposdeTramite, EmpleadoActual);
        }
        
        public void BajaTiposdeTramite(Tramites.Servicio.TiposdeTramite oTiposdeTramite, Tramites.Servicio.Empleado EmpleadoActual) {
            base.Channel.BajaTiposdeTramite(oTiposdeTramite, EmpleadoActual);
        }
        
        public System.Threading.Tasks.Task BajaTiposdeTramiteAsync(Tramites.Servicio.TiposdeTramite oTiposdeTramite, Tramites.Servicio.Empleado EmpleadoActual) {
            return base.Channel.BajaTiposdeTramiteAsync(oTiposdeTramite, EmpleadoActual);
        }
        
        public object[] ListarTiposdeTramite(Tramites.Servicio.Usuario usuActual) {
            return base.Channel.ListarTiposdeTramite(usuActual);
        }
        
        public System.Threading.Tasks.Task<object[]> ListarTiposdeTramiteAsync(Tramites.Servicio.Usuario usuActual) {
            return base.Channel.ListarTiposdeTramiteAsync(usuActual);
        }
        
        public Tramites.Servicio.Usuario BuscarUsuario(int cedula, Tramites.Servicio.Empleado EmpleadoActual) {
            return base.Channel.BuscarUsuario(cedula, EmpleadoActual);
        }
        
        public System.Threading.Tasks.Task<Tramites.Servicio.Usuario> BuscarUsuarioAsync(int cedula, Tramites.Servicio.Empleado EmpleadoActual) {
            return base.Channel.BuscarUsuarioAsync(cedula, EmpleadoActual);
        }
        
        public void AltaUsuario(Tramites.Servicio.Usuario oUsuario, Tramites.Servicio.Usuario UsuarioActual) {
            base.Channel.AltaUsuario(oUsuario, UsuarioActual);
        }
        
        public System.Threading.Tasks.Task AltaUsuarioAsync(Tramites.Servicio.Usuario oUsuario, Tramites.Servicio.Usuario UsuarioActual) {
            return base.Channel.AltaUsuarioAsync(oUsuario, UsuarioActual);
        }
        
        public void ModificarUsuario(Tramites.Servicio.Usuario oUsuario, Tramites.Servicio.Empleado EmpleadoActual) {
            base.Channel.ModificarUsuario(oUsuario, EmpleadoActual);
        }
        
        public System.Threading.Tasks.Task ModificarUsuarioAsync(Tramites.Servicio.Usuario oUsuario, Tramites.Servicio.Empleado EmpleadoActual) {
            return base.Channel.ModificarUsuarioAsync(oUsuario, EmpleadoActual);
        }
        
        public void BajaUsuario(Tramites.Servicio.Usuario oUsuario, Tramites.Servicio.Empleado EmpleadoActual) {
            base.Channel.BajaUsuario(oUsuario, EmpleadoActual);
        }
        
        public System.Threading.Tasks.Task BajaUsuarioAsync(Tramites.Servicio.Usuario oUsuario, Tramites.Servicio.Empleado EmpleadoActual) {
            return base.Channel.BajaUsuarioAsync(oUsuario, EmpleadoActual);
        }
        
        public Tramites.Servicio.Usuario LogueoUsuario(string contra, int cedula) {
            return base.Channel.LogueoUsuario(contra, cedula);
        }
        
        public System.Threading.Tasks.Task<Tramites.Servicio.Usuario> LogueoUsuarioAsync(string contra, int cedula) {
            return base.Channel.LogueoUsuarioAsync(contra, cedula);
        }
    }
}
